version: 0.2

phases:
 pre_build:
   commands:
     - echo TEST
 build:
   commands:
     # Docker Hub へのログイン
     - ls -lthra
     - pwd
     - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
     - docker run hello-world

 post_build:
   commands:
     - uname -m && uname -r && cat /etc/os-release
     # Do you need to do this? In many cases phpunit will use sqllite or similar to avoid the need for a real DB.
     # If you don't need it delete it
     # - /usr/bin/mysql  -u root -e "GRANT ALL ON *.* TO 'test'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION"
     # - mysqladmin -u test create test
     - date
